title: Contents
description: The Integrity of Federal Data
subtitle : Evaluating Disruptions to Open Government Data, 2025-2026
author: Christopher Steven Marcum, Ph.D.
theme: just-the-docs
baseurl: '/data-integrity'
url: 'https://www.chrismarcum.com'
search_enabled: true
collections:
  chapters:
    output: true
    permalink: /:collection/:name/
  terms:
    output: false
just_the_docs:
  collections:
    chapters:
      name: Report
      nav_exclude: false
      nav_fold: false
defaults:
- scope:
    path: ''
    type: chapters
  values:
    layout: chapter
aux_links:
  Repository:
  - http://www.github.com/cmarcum/data-integrity/
markdown: kramdown
kramdown:
  input: GFM
plugins:
- jekyll-scholar
scholar:
  style: apa
  locale: en
  sort_by: author
  order: ascending
  source: _bibliography
  bibliography: references.bib
  replace_strings: true
  details_link: /references/
  details_link_class: reference-link
  bibliography_template: bib
