source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.9"

# Needed for remote_theme on GitHub Pages-like builds
gem "jekyll-remote-theme"

# Inline citations + bibliography
gem "jekyll-scholar", "~> 7.0"
